### ISSUE TITLE
Host uptime not improving

### ISSUE THREAD

**Issue by MasterZeh** [TRON-US/go-btfs#1074]
Hi

Around 2 weeks ago I had a few issues with the Linux were I run one of the nodes, and since fixing them my uptime is fluctuating at 82-84% and not improving.

My host is definitely on all the time, but somehow it doesn't get reflected.
![Screenshot from 2021-06-22 05-53-36](https://user-images.githubusercontent.com/85850180/122819835-4aa8fb00-d31e-11eb-886f-cc06e787e2d4.png)

Before that my host was always on as well and I had a 100% uptime and host score of 10. Now my host score is below 8 and I'm afraid of losing contracts.

Host Node ID: 16Uiu2HAmKAZrNQ9Jjay1dkfwws2dnxvPWxidhu4RaiwTsAAyoEhp

Thank you,
Zeh

**Comment by Sophia-yu-kk** [comment]
uptime, the online time, reflects the online status of the node.
Specific calculation: uptime = actual number of node heartbeats in 30 days / total number of theoretical heartbeats in 30 days (BTFS nodes report heartbeats every 15 minutes by default, and the total number of heartbeats in 30 days is 2880)
 99% and above: 10 points
 Below 99%, 95% and above: 9 points
 Below 95%, 90% and above: 7 points
 Below 90%, 80% and above: 6 points
 Below 80%, 60% and above: 4 points
 Below 60%: 0 points
 
Because the statistics are for a month, the uptime change is not very fast, there is a process.
