### ISSUE TITLE
Withdrawal error

### ISSUE THREAD

**Issue by zarethernet** [TRON-US/go-btfs#1075]
Hello, help me to solve the problem, maybe I have something wrong.
For about 2 weeks, maybe more, I cannot transfer BTT from in-app to on-chain.
The error is always of the same type.
I am making this request:
--------------------
btfs wallet withdraw --password=password withdrawSum
--------------------

Each time the error looks like this:
--------------------
Result: Error: calling interface [TransferAsset2] error, reasons: [rpc error: code = PermissionDenied desc = Forbidden: HTTP status code 403; transport: received the unexpected content-type &quot;application/octet-stream&quot;]
--------------------

Btfs latest version:
--------------------
btfs version 1.5.1
--------------------

"ID": "16Uiu2HAmMSEYe4JmvJJ6Gjbikh87crqjXymmBeBBpyV9yoUVyBpV"

**Comment by Sophia-yu-kk** [comment]
There is currently feedback from other users with similar problems. Transfers from off-chain wallets to on-chain addresses are failing. After checking, it is because of the LEDGER service, which can only provide 1 million BTT withdrawals per day.
Exceeding this single day limit will fail and you will have to continue trying until the next day. I am not sure if this will help you. I hope so.

**Comment by zarethernet** [comment]
Thanks ;-)
