### ISSUE TITLE
Withdraw BTT from BTFS Failed...

### ISSUE THREAD

**Issue by Andrju81** [TRON-US/go-btfs#1171]
When withdraw BTT from BTFS, an error occurred and BTFS IN-APP WALLET BALANCE went to zero, but BTT never arrived at BTT CRYPTO WALLET BALANCE? My node is 16Uiu2HAkxf4zCbSFGjidcyS4zsvbqcMFAoU13ZzVi7AuCrjMGHvv.
![Clip2Net Menu_2021-11-04_01_11_18](https://user-images.githubusercontent.com/40444286/140200591-bb269640-8e48-41e6-9a03-2ec083644006.png)

**Comment by Sophia-yu-kk** [comment]
Hello, this problem is because the maximum withdrawal limit for a single day is determined, once the BTT is fully withdrawn, the subsequent withdrawal operations will fail. We suggest you to try another time.

In the meantime, we have a special solution portal for this issue. You can submit a work order at this address and the corresponding colleague responsible for the wallet withdrawal operation will assist you in solving the problem.

[](https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/)

**Comment by Sophia-yu-kk** [comment]
https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/

**Comment by Andrju81** [comment]
Every day I try to withdraw, but an error constantly occurs and the account is reset to zero, then after a while the balance is restored again!? ... Even the minimum amount cannot be withdrawn?! ...
