### ISSUE TITLE
Every day I try to withdraw BTT from BTFS, but an error constantly occurs and the account is reset to zero!?...

### ISSUE THREAD

**Issue by Andrju81** [TRON-US/go-btfs#1181]
Every day I try to withdraw BTT from BTFS, but an error constantly occurs and the account is reset to zero, then after a while the balance is restored again!?... Even the minimum amount cannot be withdrawn?!...

_Originally posted by @Andrju81 in https://github.com/TRON-US/go-btfs/issues/1171#issuecomment-963421739_

**Comment by Sophia-yu-kk** [comment]
> Every day I try to withdraw BTT from BTFS, but an error constantly occurs and the account is reset to zero, then after a while the balance is restored again!?... Even the minimum amount cannot be withdrawn?!...
> 
> _Originally posted by @Andrju81 in [#1171 (comment)](https://github.com/TRON-US/go-btfs/issues/1171#issuecomment-963421739)_

Hello, this is a known issue, the reason is because the wallet has a single day withdrawal limit, after exceeding the limit there will be withdrawal failure problem.

For this problem, we have negotiated a special solution with the wallet department. You can submit a work order for your problem through this link  https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/, and colleagues from the wallet department will specifically deal with your problem and assist you in withdrawing your assets. We apologize for any inconvenience caused to you.
