### ISSUE TITLE
V1.0 to V2.0 Migration

### ISSUE THREAD

**Issue by akinto2006** [TRON-US/go-btfs#1209]
I just want a clear understanding on what is happening. When I clicked BTFS Scan on the UI it forwards to scan.bt.io and it no longer shows the BTFS network. If you look at the addresses also, you will notice that they are not the same format as before on the TRON network. They look more like ETH or BSC addresses. How do we go about migrating our hosts and addresses to v2.0? Do we need to do anything? What of our unpaid balances?

**Comment by Sophia-yu-kk** [comment]
Hello, thank you for your interest and support of BTFS 2.0.

So far BTFS1.0 and BTFS2.0 test network are in parallel and they do not affect each other. v1.6.0 airdrop revenue is distributed normally, BTFS2.0 test network is currently in the testing phase, and BTFS2.0 official network is online before the existing nodes need to be upgraded.

Regarding your question about revenue, the airdrop rewards have been distributed normally, and the file storage revenue is being distributed in an orderly manner.

Regarding the address of BTFS2.0 test network, it is because BTFS2.0 test network supports BTTC cross-chain, please refer to our official document for details. [](https://docs.btfs.io/v2.0/docs)

**Comment by Sophia-yu-kk** [comment]
official document link is：https://docs.btfs.io/v2.0/docs
