### ISSUE TITLE
31mERROR

### ISSUE THREAD

**Issue by Nusstoertchen** [TRON-US/go-btfs#1221]
Ich bekomme diesen Fehler auch immer wieder, bitte mailen Sie mir.
←[31mERROR←[0m spin Fehler beim Synchronisieren der Hoststatistiken: Fehler beim Abfragen der Statistiken vom Hub-Dienst: HubQueryClient: rpc error: code = DeadlineExceeded desc = Kontextfrist überschritten

Peer-Identität: 16Uiu2HAmCtMgSCBzskSVQxTruXErtoeS3di7k7wfAdNeoVuhXJGn

Ich kann die BTT auch nicht von BTFS IN-APP WALLET BALANCE auf BTT CRYPTO WALLET BALANCE übertragen

**Comment by Sophia-yu-kk** [comment]
Error retrieving statistics from hub service: HubQueryClient: rpc error: code = DeadlineExceeded desc = context deadline exceeded.
This error usually disappears automatically after a few hours and does not affect contract acquisition.

The wallet withdrawal failure is due to the single day hot wallet withdrawal limit, we suggest submitting a problem feedback work order https://forum.bittorrent.com/topic/56988-important-information-on-btt-withdrawal/
