### ISSUE TITLE
Files added through CLI not showing in Web UI

### ISSUE THREAD

**Issue by sd0minick** [TRON-US/go-btfs#223]
When I add a file using the following command:

`btfs add file1.txt`

I cannot see the file when I'm looking at this link http://127.0.0.1:5001/btfs/webui

However, If I load a file or create a folder from the web ui, then I run this command in the terminal

`btfs files ls`

I can properly see the files in the CLI

Is there a way to fix this or am I missing something?

Kindly let me know your thoughts

**Comment by sd0minick** [comment]
Also when I run btfs add file1.txt. Where the file is saved? Is it on my node or on the blockain? If on my node where i-e the path.

**Comment by tycm4109** [comment]
@sd0minick Hi Steeve, thanks for letting us know. Let me take a look into it and I'll get back to you. Thx!

**Comment by sd0minick** [comment]
@tycm4109  Thanks for looking into this. Were you able to reproduce the issue? Any updates?

**Comment by tycm4109** [comment]
@sd0minick Hi Steeve, apologies for the late reply. Yes I was able to reproduce. So the way to upload a file to the WebUI via the CLI is two steps:

1. Upload the file into BTFS by running `btfs add file1.txt`
2. Add the file to the WebUI by running `btfs files cp /btfs/<file hash> /<WebUI hash>`. So for example, `btfs files cp /btfs/QmP6rWWimuobeWpG9LPME2bXiJ4t9eFyAkYLiQafNwwLCz /QmTfM7Rz58Ejwq8Yg3jEEhtLc3BBxucpATiq4pRCy6TK4J`.
3. Go to your WebUI and under the "Files" tab, you should see your newly uploaded file. Like you already mentioned, you can also run `btfs files ls` to see the uploaded file in the command line. 

I will update the docs.btfs.io documentation to guide users on this procedure, since it was asked about a few times. Please let me know if this answers your inquiry. Thx!

**Comment by sd0minick** [comment]
@tycm4109 I've tested the provided workaround and I can confirm that it works. Thanks a lot.
