### ISSUE TITLE
How to mine?

### ISSUE THREAD

**Issue by RobQuistNL** [TRON-US/go-btfs#582]
I have my daemon up and running, initialized the host, and its stating "Storage Used: 0GB Used / 9500 GB remaining".

I see the top earners of space race having 16GB? What storage counts for the space mining? Why am I not in there? This document is really unclear:
https://medium.com/@BitTorrent/btfs-will-soon-launch-storage-space-mining-on-july-7th-along-with-a-contest-of-up-to-20-billion-aa40c0919a28

It states "Each host will increase the storage capacity of 100MiB or more every day, you can join the mining bonus pool and share the total mining bonus of the day proportionally"

What does that even mean? Am I a host? Do I have to increase my storage every day? How do I join this mining bonus pool? How _can_ i mine? Or is that setting up the daemon like this?

Also, how can I add more storage disks? I have several TB's available, does everything have to be in a single linux folder?

Also, why does my host show "0 GB used", and the webui shows "Hosting 7 MB of files"?

**Comment by geoffsnyder** [comment]
@RobQuistNL I'm just an end-user, not part of the dev team, so be patient with my explanation, as it is only based on my own testing. 

First, we are 'hosting' - not mining. We are setting up 'hosts' which are part of the BTFS decentralized blockchain protocol. We are simply connecting our computers/servers to a P2P network which stores tiny bits of information.

With regard to your question as to "Why am I not on there?" - I believe the answer is you're seeing what you have allocated for availability, but you may only be host a much smaller amount. The status command will show what you are actively hosting, as well as the number of peers currently discovered. It's somewhat of a slower process from what you may be use to, as the amount of bandwidth used is very small. I've found that consistency (uptime) is the biggest factor here. I'm learning to be more patient.

Once you allocate the amount of storage you wish to rent to the network, you're done. You just sit back and let it do its thing. Obviously monitor the daemon to hangups and/or errors. 

The Mining Pool Bonus has to be an old link that got released with the 1.3.2 version because it's about 10 days old and they've been posting the winners daily. It's automatic; we're all in the 'contest', per se. Just review the explorer for Peer ID activity. I have my own questions about that for a separate conversation.   

Next, you'll probably need to stripe your hard drive(s) in order to increase your overall partition size. That single folder is essential for that partition because it contains the block, datastore, and keystore information. But it sounds like you're far from capacity at this stage, so unless you're like me and like testing the environment, there isn't really any need for you to increase your storage offering yet?

And lastly, from my experience, the webui will display a more granular storage output at first (kb/mb/gb) and it rounds that number out. The hostui only displays in GBs and does not round up for granularity... if that makes sense?

Hope this helped a little.

**Comment by RobQuistNL** [comment]
Hey Geoff,

Thanks for your extensive reply :)

Check, I do now see the "storage" in the webui rising (160MB), so there's that. I have a few contracts now, too.

So, is my assumption correct that I just need random people to store over 16GB of data on my machine, and then that makes me eligible to the rewards from the mining pool bonus?

**Comment by geoffsnyder** [comment]
I have no idea.
