### ISSUE TITLE
Lost all contracts when btfs upgraded from 1.3.4 to 1.3.5

### ISSUE THREAD

**Issue by renjithprasad** [TRON-US/go-btfs#627]
#### Version information:
go-btfs version: 1.3.5-20c165c
Repo version: 9
System version: amd64/windows
Golang version: go1.14.6

#### Description:
Node upgraded from 1.3.4 to 1.3.5. 
1.3.4 version GUI was showing 262 contracts with around 984 BTT in contract wallet.
After upgrade, showing only 1 contract with 4 BTT in contract wallet.

1.3.4 payment date was Aug 18 and after upgrade it changed to Sept 08.

Node Id: 16Uiu2HAmQaqSZXNb3zCLAijN23CAxeR4PZsBypmQWxJwuQweGi8o

**Comment by taiyangc** [comment]
See #626 This is expected. What you saw in v1.3.4 was inaccurate.

**Comment by renjithprasad** [comment]
The total data that i can view on webui page is 5GB. And i have set host rate at 7000BTT/TB. So if i do the calculation i am getting around 35BTT for the 5GB shard data that i am hosting. How is it 4BTT for 5GB data that i am hosting ?

Thanks

**Comment by taiyangc** [comment]
The data you saw from webui merely means the total number of files you have stored on your host. It does not mean that these files are fully paid for. For example, you can perform `btfs add <big-file>` (this operation involves no payment) and you will see that number increase.

Now in the realistic case here that you did receive 5GB of files from other renters, however, there are many reasons why it is not considered active: 1) it could not be challenged due to your host port unreachable 2) the contract was not paid in full by renter 3) contract was canceled due to too many shards are lost on the network, and etc.

To verify, you can run `btfs storage contracts list host` to see how many active contracts you have. To see all contracts, run `btfs storage contracts list host --status=all`. You can check the `Status` field of each contract against this map (https://github.com/TRON-US/go-btfs/blob/master/core/commands/storage/helper/contracts.go#L5) to understand which category the status falls under, and each const defined tells you which step this contract is on.

**Comment by kvasselkvasier** [comment]
So what do we do with the storage files that we don't have contracts for. For me I have 80gb in host ui and 1 contract. When will the files be deleted from my host? Or is there a command to delete those file with no contract?

**Comment by taiyangc** [comment]
@kvasselkvasier Currently we don't have a dedicated command to delete files without contract. The best approach right now is to run `btfs storage announce -m=100` to limit the max size you are willing to store. Any invalid/uncontracted files will be overwritten by actual contracted files. We will work on a better command to purge uncontracted files.

**Comment by kvasselkvasier** [comment]
@taiyangc thanks for the info.
