### ISSUE TITLE
File sharing URL is missing gateway.btfs..

### ISSUE THREAD

**Issue by GodDamndammit** [TRON-US/go-btfs#67]
Hi,

After adding a file and selecting the option to share it, the link that is generated is wrong.

The correct link should start with https://**gateway**.btfs.trongrid.io and its missing..

![image](https://user-images.githubusercontent.com/52445303/60494768-56b9cf00-9ca7-11e9-9bc1-b8c97fb94165.png)

This leads to a "This site can’t be reached" error..

Thank you!

**Comment by GodDamndammit** [comment]
![image](https://user-images.githubusercontent.com/52445303/60496483-d006f100-9caa-11e9-991c-f623980db28c.png)

I would assume this is where the changes need to be made but since the files they are being served by remotely (Which is awesome) there is no way to make a commit.

**Comment by tycm4109** [comment]
@GodDamndammit Thanks man! I've updated the URL. However, unfortunately, it won't be reflected in the binary package until the next version release, which should be soon. I'll keep the issue open until then. Thx.

**Comment by GodDamndammit** [comment]
> @GodDamndammit Thanks man! I've updated the URL. However, unfortunately, it won't be reflected in the binary package until the next version release, which should be soon. I'll keep the issue open until then. Thx.

No problem! A test phase is exactly for these things. Thank you for the prompt feedback. 

Cheers

**Comment by zillerium** [comment]
I have the same issues. What is the URL now for the gateway?

**Comment by kevin-yuhh** [comment]
gateway.btfssoter.io  is the latest gateway URL.

**Comment by miaryafar** [comment]
I have same problem!
btfs getdway DON'T work at All !

the sample of documentary Don't work for months : 
https://gateway.btfs.io/btfs/QmbS5ZN8oPULLxQHC426WLL8HuxvbaNqvKKSxpNAURwEt8
https://docs.btfs.io/docs/btfs-gateway-user-guide

i'm not sure that project work at All.
do you have any data about that?
I Like this project but i'm not sure is there any body support it or not.
I should use IPFS instead of BTFS and it not as good as BTFS business plan.
I hope that BTT start to work again !
