### ISSUE TITLE
How do I opt-out of analytics collection?

### ISSUE THREAD

**Issue by lanzafame** [TRON-US/go-btfs#69]
There seems to be no way to opt-out of the collection of telemetry?

**Comment by tycm4109** [comment]
@lanzafame Hi Adrian, the telemetry data is aggregate performance data that helps our engineering team to characterize and identify potential health and performance metrics that may degrade over time. We use this data as a guide in the BTFS development process. 

As you are well aware, many distributed protocols can be particular resource hogs when the client is set up locally. One of our goals is to actively work on optimizing these issues for improved user experience, particularly for folks who require a client running for extended periods of time. To answer your question, at this point, there is no opt-out, since it is just anonymous health and performance data. 

However, we are working on an opt-out option, which will be released in the future for users to use. Thank you.

**Comment by vaultec81** [comment]
Telemetry data gathering can be easily removed from the source code. If needed.
