### ISSUE TITLE
Cannot import/create Wallet in BTFS HostUI

### ISSUE THREAD

**Issue by newvinaut** [TRON-US/go-btfs#703]
#### Version information:

go-btfs version: 1.3.6-b1722d1
Repo version: 9
System version: amd64/linux
Golang version: go1.14.6
OS: Ubuntu 18.04.5 LTS

#### Description:
When trying to import a wallet using passphrase, "System Error -  Please try again later" is displayed.

When trying to create a wallet, a password is typed in, but when I click on "Continue", nothing happens.

**Comment by andreas-barthel** [comment]
Hi.
Did you access the Host-UI via remote? I'm asking because the Wallet-API is not accessable via Intra-/Internet. (only localhost works) In such a case you can use the CLI for importing a wallet. If you don't want to import a wallet you can the wallet as it is. The init command has already created a wallet for you. (Yes, it is shown as "uninitialized", but you can use it).

**Comment by newvinaut** [comment]
Yes, it was remote. Thanks for clarifying that. 

For CLI wallet importing, is this documented somewhere?

**Comment by andreas-barthel** [comment]
Unfortunately, it is not documented on the documentation-website.
But you can use the CLI for help:
`btfs wallet --help` (on Linux) or
`btfs.exe wallet --help` (on Windows).
Each subcommand has a `--help` flag too.
If you really need to access the Wallet API  on remote, then you can install a so called "Reverse Proxy". For example nginx.
I assume that the Wallet API maybe can accessed in future releases of BTFS. But @taiyangc can tell more about this.

**Comment by taiyangc** [comment]
Remote access is not allowed due to security reasons. Please run wallet ui on localhost.
