### ISSUE TITLE
Extending or renewing existing contract

### ISSUE THREAD

**Issue by nyanpass519** [TRON-US/go-btfs#757]
Hi,

I am struggling to handle contracts on btfs and I cannot find information on how to extend or renew existing contract.

What I would like to do is following:
1. Upload files as a renter for a 30 day contract.
$ btfs storage upload Qm ...
2. Just before the end of contract (say 1 day before), extend/renew the contract without making none-contract period and without downloading the previously uploaded files to re-upload.

I have tried upload files which I had already uploaded a week ago, but upload status showed error as below.
$ btfs storage upload status ...
{"Status":"error","Message":"GuardClient: rpc error: code = Unknown desc = Persistence manager: such file hash already exist for such renter" ...

How can I extend or renew existing contract?

**Comment by JustinGaoF** [comment]
@nyanpass519 yes, you met the issue because of function release milestone, and sorry for any inconvenience it caused. 

To avoid the renter wrongly submit the same file, BTFS did not accept the same file from same renter; and for the renew function, which was planned to be released this quarter. These things caused your current issue.  Now we are working on the renew function testing, it will be released soon, hope the renew function release can eventually solve your issue.

**Comment by nyanpass519** [comment]
Thank you for the reply. I'm relieved to hear the release plan.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
