### ISSUE TITLE
some question about new airdrop

### ISSUE THREAD

**Issue by boringw** [TRON-US/go-btfs#772]
according to   https://medium.com/@BitTorrent/btfs-airdrop-distribution-rules-update-9ea0dea7d0f5

“If BTFS has detected any cheating behavior or host that denied access, no airdrop will be distributed afterward.”

q 1: cheating behavior must block，this is no problem，but host that denied will be blocked? mybe network is wrong when check

q 2: the airdrop Extend to 150day， so if some cheating miner is blocked on 50day，they  Remaining airdrop will be redistribute to onther miner?

q 3:the airdrop Extend to 150day，but the contract smallest can upload is 30day，so this will how to do airdrop?

Looking forward to your reply，thanks

**Comment by endofthepain** [comment]
yeah the problem is default contract is 30 days

**Comment by boringw** [comment]
another question the airdrop Extend to 150day， maybe one time airdrop need check contracts will be increase to a big number，so how to  ensure  airdrop running well

**Comment by endofthepain** [comment]
i think we are never got answer about this question, "After more detailed discussion and community feedback review" we dont know the community from where because we can look discord / telegram / twitter there no btfs team asking question asking suggestion i think is just self claim by btfs team

**Comment by boringw** [comment]
> i think we are never got answer about this question, "After more detailed discussion and community feedback review" we dont know the community from where because we can look discord / telegram / twitter there no btfs team asking question asking suggestion i think is just self claim by btfs team

"community" maybe reddit

**Comment by boringw** [comment]
![20201105172846](https://user-images.githubusercontent.com/46474646/98223165-b192c300-1f8c-11eb-91f2-a1dce6e98f93.png)

see this, if my node in 50 day get 50GB upload data, so every time airdrop host Challenge request will read my all data? this just my guess, is true?

if true, It's a disaster for some vps，because they have no fast io speed

**Comment by JustinGaoF** [comment]
I am the person from BTFS who work for airdrop, let me try to answer your questions, but it should not be official.

q 1: cheating behavior must block，this is no problem，but host that denied will be blocked? maybe network is wrong when check
Answer: host denied here mean the host deny the storage challenge, and if it is network wrong, it will be marked as a timeout response, which will followed by retry in given time. And we have a principle that if server got only timeout response in 7 days, the storage will be marked as lost. 

q 2: the airdrop Extend to 150day， so if some cheating miner is blocked on 50day，they Remaining airdrop will be redistribute to onther miner?
Answer: yes, cheating behavior of course will not be rewarded, and need to be punished.  If we find the host is cheating, we will stop all all airdrop related to this host. And please trust us, we have conclude solid reason for adding the host in the blocklist, so that we can guarantee every host added is a true cheater. 

q 3:the airdrop Extend to 150day，but the contract smallest can upload is 30day，so this will how to do airdrop?
Answer: the btfs have argument to change the contract length from 30 days to 150 days. From airdrop view, it is just check whether the file exist more than 150 days with right contract cover, if it is, do related reward.

**Comment by JustinGaoF** [comment]
> ![20201105172846](https://user-images.githubusercontent.com/46474646/98223165-b192c300-1f8c-11eb-91f2-a1dce6e98f93.png)
> 
> see this, if my node in 50 day get 50GB upload data, so every time airdrop host Challenge request will read my all data? this just my guess, is true?
> 
> if true, It's a disaster for some vps，because they have no fast io speed

No, it is just re-hash the chunk which is smallest part of the file stored in harddisk, every chunk should be static 256KB.

**Comment by boringw** [comment]
> I am the person from BTFS who work for airdrop, let me try to answer your questions, but it should not be official.
> 
> q 1: cheating behavior must block，this is no problem，but host that denied will be blocked? maybe network is wrong when check
> Answer: host denied here mean the host deny the storage challenge, and if it is network wrong, it will be marked as a timeout response, which will followed by retry in given time. And we have a principle that if server got only timeout response in 7 days, the storage will be marked as lost.
> 
> q 2: the airdrop Extend to 150day， so if some cheating miner is blocked on 50day，they Remaining airdrop will be redistribute to onther miner?
> Answer: yes, cheating behavior of course will not be rewarded, and need to be punished. If we find the host is cheating, we will stop all all airdrop related to this host. And please trust us, we have conclude solid reason for adding the host in the blocklist, so that we can guarantee every host added is a true cheater.
> 
> q 3:the airdrop Extend to 150day，but the contract smallest can upload is 30day，so this will how to do airdrop?
> Answer: the btfs have argument to change the contract length from 30 days to 150 days. From airdrop view, it is just check whether the file exist more than 150 days with right contract cover, if it is, do related reward.

very thanks your replay， it is good news for normal miners

last question

https://medium.com/@BitTorrent/btfs-will-soon-launch-storage-space-mining-on-july-7th-along-with-a-contest-of-up-to-20-billion-aa40c0919a28
in this page ，“If the total storage will be 1PiB or more, 1,000 Hosts will share 5 billion BTT based on increased storage ratios” is it true？still valid?  and every day airdrop when will it end?

**Comment by JustinGaoF** [comment]
I am not the person can answer the question you referred, it need market team give official answer.

I believe all this is on plan, and I can not for-see the airdrop's end now. But again, I am not person can give the official answer, so it's ok for you to take my words for your question as rumor.

**Comment by boringw** [comment]
> I am not the person can answer the question you referred, it need market team give official answer.
> 
> I believe all this is on plan, and I can not for-see the airdrop's end now. But again, I am not person can give the official answer, so it's ok for you to take my words for your question as rumor.

very thanks your help
