### ISSUE TITLE
Have not received any airpdrops from the new reward round.

### ISSUE THREAD

**Issue by geoffsnyder** [TRON-US/go-btfs#786]
Based on the recent update via Medium, airdrop rewards were to being November 5th. I have not seen any distributed across any of the nodes we're maintaining. Ideas... thoughts?

**Comment by endofthepain** [comment]
host must get minimum 100 MiB file storage everyday

**Comment by geoffsnyder** [comment]
All of our nodes have far exceeded that. Thanks

**Comment by taiyangc** [comment]
Can you provide at least one host id which you believe has exceed 100MB and on which day? thanks.

**Comment by geoffsnyder** [comment]
> Can you provide at least one host id which you believe has exceed 100MB and on which day? thanks.

16Uiu2HAm9unWsDcBMxWA8KoqkGj1raUcQDW6s1u7f5XpRnSAeifR - several days before, during , and after the initial new programs. 11/3 thru 11/9

**Comment by geoffsnyder** [comment]
Response?

**Comment by taiyangc** [comment]
Your node is normal. We did not find anything odd other than that the node is not receiving *new* uploads since mid September.

**Comment by geoffsnyder** [comment]
That seems odd, as it definitely has received uploads since mid-September.
Probably even moreso than ever.

How are you checking?

**Comment by taiyangc** [comment]
We checked all of this node's contracts that exist in our system and none came after September. Unless you can provide a contract id + node id that was created recently, we can investigate further.

**Comment by geoffsnyder** [comment]
Can you show/tell me what you use to audit that?

I ask because we've kept a close eye on the overall metrics and there seems
to be a lot of of inconsistences with what you are staying.

For example, conservatively speaking, this node in particular has had
roughly 12 new contracts added just within the last week. September we were
at roughly 50 overall contracts.

If you can provide me with an example and or the process for the
information you're requesting, I'll gladly forward it to you.

Hopefully you understand my concern, as we've had roughly 70 nodes within
our data center dedicated for testing your releases since June of this
year. The expense for the upkeep is obviously a negative, regardless of
long-term forecasting.

**Comment by JustinGaoF** [comment]
From central system's record, the node 16Uiu2HAm9unWsDcBMxWA8KoqkGj1raUcQDW6s1u7f5XpRnSAeifR had not receive any contracts after Sep. And from other view, the host is storing more than 800 shards related to active contracts.  Based on current airdrop methodology, it should receive big amount of airdrop every day if the proof of replication challenge can be executed right, but unfortunately, it was not good enough to get the challenge done in timeout.  So if you can, try to get the host in good maintenance so that our system can understand the file's existence which will get host airdrop reward. 

Back to your question, if the host really receive 12 new contracts last week, kindly share me one contract's shardhash + contract id, so that  we can check which issue caused such confusion.

BTW, from the system's record, we believe the node is a good host in BTFS network, which we try to reward more with building fair process. Thank you for kindly support.
