### ISSUE TITLE
What happens if multiple renters rent hosting for the same file?

### ISSUE THREAD

**Issue by balupton** [TRON-US/go-btfs#864]
Use case:

> Coincidentally, User A and User B, unknown to each other, have both downloaded File Z from the traditional web, they both wish to replicate it to the cloud in a decentralised and p2p fashion so the file exists with redundancy, without the need to run seed it via torrent on their local machine, as they both have laptops which turn off from time to time. They both discover BTFS and decide to store the file on BTFS hosts via the renting procedure.

What happens here?

1. Do they split the payment for this? Paying half?
2. Do their requirements for term and redundancy double for free?
3. Do they both get charged the same, with no extra redundancy or term limit?

BTFS provides a good opportunity for say mirroring youtube videos in a decentralised way, however without outcome 1 or outcome 2 being the case, seeding via traditional torrent clients seems a better fit.

**Comment by taiyangc** [comment]
They are charged the same separately because payment is required by storage hosts. Ideally, hosts could observe that the exact file is being stored and be somewhat smart about a "reduce payment". However, because of availability and reliability concerns, not the exact list of hosts may be used to storage the file shards, and if we enforce hosts to de-duplicate and combine file storage terms, it would further complicate the contracts - e.g. what happens if the paying user has 3 month term but the 2nd user wants 4 month, who pays for what portion, and dynamically splitting the bill is not easy.

Of course, to achieve decentralization of videos like you mentioned, there is another route which is to simply host file shards for free so users can freely stream/download videos (similar to Bittorrent). But hosts would then lose the incentive to satisfy the availability and reliability required by paying users.
