### ISSUE TITLE
30+TB BTFS onlined. Transferred funds gone. Zero contracts. What is going on?

### ISSUE THREAD

**Issue by EmersonOrion** [TRON-US/go-btfs#958]
Please check address TZ9xFms9DK1nCteN8747Pyc4ckHPB4Gkcr
Peer 16Uiu2HAmM5VRt2qGqhB3pZqg8hEKmrwqWiCjigt1zucQmUXUKP4C.
15k BTT was transferred into BTFS Wallet, status still pending.
No smart contracts initiated: Status Fail
Still 0 contracts, Balance 0 in wallet, 1.9BTT in app, now missing 15k BTT+ no contracts for 4 days.

{"id":"67266","time_create":"2021-03-21T22:16:59.8487746Z","amount":15000000000,"from":"BTT Wallet","to":"BTFS Wallet","status":"Pending"}

**Comment by EmersonOrion** [comment]
Hello. 
Where is my transfer?
It has been almost a week.
Smart Contract Status is Fail.
Please advice.
Regards.
![image](https://user-images.githubusercontent.com/81196017/112733869-a3275280-8eff-11eb-80ab-caeaf44b85b4.png)

**Comment by laipogo** [comment]
Thank you for your patience.
Will look into it asap.
We guarantee you won't lose the money.

**Comment by EmersonOrion** [comment]
Thank you. I continue to keep node running. Still has no contracts and TRON explorer say Contract Status Fail. :(

**Comment by EmersonOrion** [comment]
Now see:
![image](https://user-images.githubusercontent.com/81196017/113361054-e880c100-92ff-11eb-81cf-5d73a91f31f5.png)

Did you see a problem yet? Thank you.

**Comment by DarkBlaez** [comment]
Did you get an answer? I'd be real curious if you get a response. I have yet to see definitive responses to issues or follow ups to commentary

**Comment by EmersonOrion** [comment]
I receive no response but last. 30TB of space allocated on 10 gbits line. 1 month. No contracts, 12 days waiting and still missing funds. No response from devs team. I wait one more days then I switch off node. Say hosting 280MB files, 8gbytes transfer wasted. Seems a waste of time, power, resource and now 15,000 BTT purchase cost of over $50 because instruction say node require deposit.

**Comment by DarkBlaez** [comment]
I am thinking BTFS is a waste of time. The forked most of the IPFS git repo for the core. The BTFS webui is the IPFS WebUI with a name change and actually they turned off functionality or could not even port it to the point where the full functionality is working. The distributed storage is all IPFS as well. Most of the storage you are seeing is all IPFS files. The primary network is all IPFS. Again, thing IPFS with a name change. The layering of token is more of a gimmick. I do not see any success in BTFS. There is a reason the developers have not responded, to fork a project and actually loose functionality and not understand a number of the issues does not give me much faith in the effort. Then again just because someone is associated with something new does not mean they are a seasoned or experienced developer. The 280MB you are storing is all IPFS. You most likely will see a UFO land than to get a BTFS contract. If you look at the early nodes they are tainted which is why you see the large amount of BTT indicated in their earnings. Nearly the same has holding back crypto during an ICO. The number of individuals running nodes that are not associated with the core project are not seeing contracts.

I am leaving my node run as a bet with another that I won't see any contracts at all. I have other nodes running supporting the IPFS network which I am seeing a lot of development around. It's been very well established, a great community, very responsive and supportive. This is the primary reason this project chose to fork IPFS for BTFS.

-DB

**Comment by EmersonOrion** [comment]
Yes. I am aware of all the risks. It is fork of IPFS. That is fine. A fork is a fork. I am O K to have tokenization for payment. That is fine too. I think it can add value to host. However it looks like devs is not skilled or understand IPFS so they just tack on tokenization they don't understand also to IPFS and say "it's done" but it has many problem and they do not understand enough to fix it. I run FIL, STORJ and SIA already. This is much better. I figure BTT is just long shot but I did try it anyway why not. I have extra resource and it did not take away from other areas, but if I do not hear resolution in 24h it will be reallocated to FIL or STORJ. Already suspect BTT and Bittorrent integrate to uTorrent which is garbage ware. Same for Bittorrent client is garbage ware these days. It seems they don't understand to fix the TRON contract. It's contracts are failed. All this has to be done is unpause/reinitiate the contract. I feel maybe it did work before, but when the BTT price goes up they just disable the contract for new host. Then it requires deposit to start node, but new host can't withdraw from contract pool. TRON contract address has $200,000+ USD BTT. Transfer completed, but no contract means no funds can be withdraw. I figure I try it, I ask to fix it, I wait patiently, no response I just move to something else. Appreciate your response.

**Comment by DarkBlaez** [comment]
I really have no faith in the developers, they rely on the IPFS fork for many of the updates and issue resolution. They do not implement a daemon correctly, the core of btfs has a tendency to crash without providing error, they compile for a number of architectures but I wonder if they actually test them fully. I support STORJ and SIA with nodes as well. However, I will let this BTFS node run to see what comes of it but no longer than a week. I will set pricing to a very low number to see truly how the contracts get parceled out. I have my suspicions and think BTFS/BTT is a rabbit hole that will never churn any gain.

Long term I will support IPFS with nodes just to provide something back to the community at my expense. I hope you get a response but it seems the developers and maintainers avoid the truly complex issues, questions, and commentary. My hype than delivery.

-DB

**Comment by DarkBlaez** [comment]
By the way the score is not anything that is accurate. My uptime keeps going down, yet my new node has been up 100%. Now its at 81%. Being honest, BTFS is starting to appear more and more like crap which is what the general assessment from others is. They are off to a bad start and again since rarely do we see responses or commentary, I'd have to surmise the developers are in over the heads and cannot pull this off. It's a patchwork of someone else's work and efforts all patched together. I will be retiring this node since there is absolutely no way I would expect myself or anyone else to see contracts.

-DB

**Comment by EmersonOrion** [comment]
Yes. I disable node today. Where is devs? It is 13 days? It is waste of time. There is too many problems. Devs don't fix. 13 day missing funds only if they will unpause contract or restart. This is all to be done but I see many others missing funds now. It possible they take funds from network host who buys into network then sell token back to market and use new money to pump BTT token. BTT looks like pump scheme.

**Comment by DarkBlaez** [comment]
Yes it seems like a scheme to pump BTT. I have disabled my node. I am going to just remove the BTFS crap and set it up as an IPFS node and then start another IPFS gateway to support the IPFS community. BTFS wasted much of my time, but in seeing the developers hide and nothing but Medium articles and hype, it has disaster written all over it. Best wishes EmersonOrion, I hope you get your funds back.

-DB

**Comment by EmersonOrion** [comment]
Yes, but people do not do research. Hype can drive too many thing in crypto because of a medium article. People think medium is some kind of news but anyone can post article and real article is mixed in. It's the problem crypto always face because people think to get rich by tomorrow, not in 10 year. "Bez práce nie sú koláče" means "No hard work, no cake." but people want cake easy. I buy in very low, so the loss is very small but it's nice to get funds back because price increase but I do not hold my breath else I die from not breathing! Best to you also DarkBlaez.

**Comment by DarkBlaez** [comment]
Thanks. I agree, the crypto adventure always sees individuals that think they have built the better mousetrap, they are eager to envision their ideas, fall short on implementation, start the public relations hype, then struggle to get close to the original tenants of the effort. When you have an entire project that is a derivative of someone else's work, nearly a mirror copy with about 20% value-add, often those projects fail. BTFS is a great case study in what happens when developers have little to no familiarity with a code base and merely forked as the foundation. I have pulled the plug on my node and will divert it to support the community BTFS was copied from, IPFS. Best wishes EmersonOrion, it's been a interesting ride. As you say, Bez práce nie sú koláče (I like the saying)

-DB

**Comment by EmersonOrion** [comment]
25 days still no update. Maybe it seems a better investment long term instead of BTT to buy dogecoin at 35 cents.

Its nice if BTT dev would have funds returned already.

**Comment by EmersonOrion** [comment]
I bump this again to top so new people can see problem exist with BTT. Will devs ever return funds? Probably not but can let other know to have cautions.

**Comment by EmersonOrion** [comment]
i will bump this again because it is not resolve and new people to btt should know it has problem

**Comment by EmersonOrion** [comment]
one more time i bump this again. hello devs. new buyer for btt and people who set up node need to know it has problem.

**Comment by EmersonOrion** [comment]
i bump this again. it is 3 months. dev still has not returned funds of missing btt in account. new btt investor need to know btt has issue.

**Comment by Sophia-yu-kk** [comment]
The system will automatically close the longer issues, if your problem is still not solved, you can join the discord group chat: https://discord.gg/2CwVmm5X
