### ISSUE TITLE
No Contracts

### ISSUE THREAD

**Issue by irahulranjan** [TRON-US/go-btfs#982]
Hi, 
I have a 7+ score and 100% up time, still I have not got any contracts. I don't know whether its a bug or not.
Is there any way to check if I will be getting contracts?

**Comment by steelvirus** [comment]
I would not expect too much of an answer from someone working on this project. It takes a while, for me it took about a month until the first contracts came in. I am now at a score of 10 on all my nodes and have not gotten any contracts for almost a month. My issue got closed with an explanation not even related to my problem. 

Don't put too much energy and money into this, it really is not worth it.

**Comment by irahulranjan** [comment]
@steelvirus The hostage for me always shows as 0, any idea why that is or when it will increase?

**Comment by laipogo** [comment]
> @steelvirus The hostage for me always shows as 0, any idea why that is or when it will increase?

When your host has kept on line for more than 7 days.

**Comment by irahulranjan** [comment]
@laipogo Thanks! 
Did you get any contracts.

**Comment by Sophia-yu-kk** [comment]
Renters will randomly select Hosts by their score and geo when they upload files. Since the number of eligible Hosts is large (details can be found at https://scan.btfs.io), we cannot guarantee the number of contracts for each Host. However, with the expansion of the BTFS community and use cases, more contracts will come.

**Comment by Sophia-yu-kk** [comment]
> Hi,
> I have a 7+ score and 100% up time, still I have not got any contracts. I don't know whether its a bug or not.
> Is there any way to check if I will be getting contracts?

Renters will randomly select Hosts by their score and geo when they upload files. Since the number of eligible Hosts is large (details can be found at https://scan.btfs.io), we cannot guarantee the number of contracts for each Host. However, with the expansion of the BTFS community and use cases, more contracts will come.
